live_config_reload = true

[window]
opacity = 0.85
dynamic_padding = false
decorations = "buttonless"

[window.padding]
y = 20
x = 20

[font]
normal = { family = "GohuFont uni11 Nerd Font Mono" }
size = 13
